// ── 계명대학교 강의 더미 데이터 ──
// 실제 서비스에서는 EDWARD/학교 API 응답을 이 형태로 맞춰 연결하면 됩니다.
export const lectureCatalog = [
  {
    id: 'KMU-CSE3102-01',
    lectureCode: '31020',
    sectionCode: '01',
    name: '데이터베이스',
    professor: '김요한',
    room: '공학1호관 3102',
    credit: 3,
    category: '전공',
    college: '공과대학',
    department: '컴퓨터공학과',
    capacity: 45,
    enrolled: 38,
    successRate: 84,
    color: '#ECF9C8',
    meetings: [
      { day: '월', startHour: 9, endHour: 11 },
      { day: '수', startHour: 14, endHour: 16 },
    ],
  },
  {
    id: 'KMU-CSE1402-01',
    lectureCode: '31402',
    sectionCode: '01',
    name: '운영체제',
    professor: '김요한',
    room: '공학1호관 1402',
    credit: 3,
    category: '전공',
    college: '공과대학',
    department: '컴퓨터공학과',
    capacity: 40,
    enrolled: 36,
    successRate: 78,
    color: '#D9F1E8',
    meetings: [
      { day: '목', startHour: 9, endHour: 11 },
      { day: '월', startHour: 15, endHour: 17 },
    ],
  },
  {
    id: 'KMU-CSE2019-01',
    lectureCode: '32019',
    sectionCode: '01',
    name: '컴퓨터네트워크',
    professor: '사공상욱',
    room: '공학1호관 2019',
    credit: 3,
    category: '전공',
    college: '공과대학',
    department: '컴퓨터공학과',
    capacity: 40,
    enrolled: 33,
    successRate: 72,
    color: '#FDE3E3',
    meetings: [
      { day: '월', startHour: 11, endHour: 13 },
      { day: '수', startHour: 16, endHour: 18 },
    ],
  },
  {
    id: 'KMU-CSE3127-01',
    lectureCode: '31270',
    sectionCode: '01',
    name: '웹어플리케이션구축',
    professor: '김요한',
    room: '공학1호관 3127',
    credit: 3,
    category: '전공',
    college: '공과대학',
    department: '컴퓨터공학과',
    capacity: 35,
    enrolled: 31,
    successRate: 68,
    color: '#DAE8F8',
    meetings: [
      { day: '화', startHour: 13, endHour: 15 },
      { day: '목', startHour: 10, endHour: 12 },
    ],
  },
  {
    id: 'KMU-CSE1302-01',
    lectureCode: '31302',
    sectionCode: '01',
    name: '소프트웨어공학',
    professor: '사공상욱',
    room: '공학1호관 1302',
    credit: 3,
    category: '전공',
    college: '공과대학',
    department: '컴퓨터공학과',
    capacity: 45,
    enrolled: 27,
    successRate: 91,
    color: '#F3E7E7',
    meetings: [
      { day: '화', startHour: 10, endHour: 11 },
      { day: '목', startHour: 16, endHour: 17 },
    ],
  },
  {
    id: 'KMU-CSE2104-02',
    lectureCode: '21040',
    sectionCode: '02',
    name: '자료구조',
    professor: '이서연',
    room: '공학1호관 2201',
    credit: 3,
    category: '전공',
    college: '공과대학',
    department: '컴퓨터공학과',
    capacity: 40,
    enrolled: 39,
    successRate: 61,
    color: '#FFE8A3',
    meetings: [
      { day: '화', startHour: 14, endHour: 16 },
      { day: '금', startHour: 9, endHour: 11 },
    ],
  },
  {
    id: 'KMU-GSW10708-02',
    lectureCode: '10708',
    sectionCode: '02',
    name: '객체지향프로그래밍',
    professor: '조현철',
    room: '덕7402',
    credit: 3,
    category: '전공',
    college: '공과대학',
    department: '게임소프트웨어학과',
    capacity: 35,
    enrolled: 30,
    successRate: 74,
    color: '#D7F7F4',
    meetings: [
      { day: '월', startHour: 16, startMinute: 30, endHour: 18, endMinute: 20 },
      { day: '수', startHour: 16, startMinute: 30, endHour: 18, endMinute: 20 },
    ],
  },
  {
    id: 'KMU-GSW22882-01',
    lectureCode: '22882',
    sectionCode: '01',
    name: '게임물리',
    professor: '성만규',
    room: '덕7418',
    credit: 3,
    category: '전공',
    college: '공과대학',
    department: '게임소프트웨어학과',
    capacity: 35,
    enrolled: 26,
    successRate: 82,
    color: '#FCE7F3',
    meetings: [
      { day: '월', startHour: 13, startMinute: 30, endHour: 14, endMinute: 45 },
      { day: '수', startHour: 9, startMinute: 0, endHour: 10, endMinute: 15 },
    ],
  },
  {
    id: 'KMU-DIG26423-01',
    lectureCode: '26423',
    sectionCode: '01',
    name: 'GAME IMPLEMENTATION TECHNIQUES(영어강의)',
    professor: 'Holmes, Jonathan Royce',
    room: '덕7405',
    credit: 3,
    category: '전공',
    college: '공과대학',
    department: '디지펜게임공학과',
    capacity: 30,
    enrolled: 22,
    successRate: 80,
    color: '#EDE9FE',
    meetings: [
      { day: '화', startHour: 14, startMinute: 0, endHour: 15, endMinute: 15 },
      { day: '금', startHour: 14, startMinute: 0, endHour: 15, endMinute: 15 },
    ],
  },
  {
    id: 'KMU-DIG26426-01',
    lectureCode: '26426',
    sectionCode: '01',
    name: 'PROJECT I(영어강의)',
    professor: 'Holmes, Jonathan Royce',
    room: '덕7405',
    credit: 3,
    category: '전공',
    college: '공과대학',
    department: '디지펜게임공학과',
    capacity: 30,
    enrolled: 20,
    successRate: 78,
    color: '#E0F2FE',
    meetings: [
      { day: '화', startHour: 10, startMinute: 30, endHour: 11, endMinute: 45 },
      { day: '목', startHour: 16, startMinute: 30, endHour: 17, endMinute: 45 },
    ],
  },
  {
    id: 'KMU-BIZ2201-01',
    lectureCode: '22012',
    sectionCode: '01',
    name: '마케팅원론',
    professor: '윤지훈',
    room: '의양관 214',
    credit: 3,
    category: '전공',
    college: '경영대학',
    department: '경영학과',
    capacity: 50,
    enrolled: 41,
    successRate: 82,
    color: '#E5DBFF',
    meetings: [
      { day: '수', startHour: 9, endHour: 11 },
      { day: '금', startHour: 13, endHour: 15 },
    ],
  },
  {
    id: 'KMU-ENG1103-01',
    lectureCode: '11030',
    sectionCode: '01',
    name: '영문학개론',
    professor: '최하늘',
    room: '영암관 303',
    credit: 3,
    category: '전공',
    college: '인문국제학대학',
    department: '영어영문학과',
    capacity: 35,
    enrolled: 20,
    successRate: 92,
    color: '#D7F7F4',
    meetings: [
      { day: '금', startHour: 15, endHour: 17 },
    ],
  },
  {
    id: 'KMU-GEN1001-01',
    lectureCode: '10001',
    sectionCode: '01',
    name: '채플(1)',
    professor: '이은혜',
    room: '아담스채플',
    credit: 0,
    category: '교양',
    liberalType: '공통교양',
    liberalArea: '채플(1)',
    capacity: 200,
    enrolled: 152,
    successRate: 98,
    color: '#E0F2FE',
    meetings: [
      { day: '월', startHour: 13, endHour: 14 },
    ],
  },
  {
    id: 'KMU-GEN1002-01',
    lectureCode: '10002',
    sectionCode: '01',
    name: '스마트비즈니스와창업기초',
    professor: '김도윤',
    room: '쉐턱관 101',
    credit: 2,
    category: '교양',
    liberalType: '공통교양',
    liberalArea: '스마트비즈니스와창업기초',
    capacity: 80,
    enrolled: 66,
    successRate: 90,
    color: '#FDE68A',
    meetings: [
      { day: '화', startHour: 11, endHour: 13 },
    ],
  },
  {
    id: 'KMU-GEN1205-02',
    lectureCode: '12051',
    sectionCode: '02',
    name: 'COLLEGE ENGLISH I',
    professor: 'Sarah Kim',
    room: '쉐턱관 202',
    credit: 2,
    category: '교양',
    liberalType: '공통교양',
    liberalArea: 'COLLEGE ENGLISH I',
    capacity: 30,
    enrolled: 24,
    successRate: 87,
    color: '#EDE9FE',
    meetings: [
      { day: '화', startHour: 9, endHour: 11 },
    ],
  },
  {
    id: 'KMU-GEN1206-01',
    lectureCode: '12052',
    sectionCode: '01',
    name: 'COLLEGE ENGLISH II',
    professor: 'Michael Lee',
    room: '쉐턱관 203',
    credit: 2,
    category: '교양',
    liberalType: '공통교양',
    liberalArea: 'COLLEGE ENGLISH II',
    capacity: 30,
    enrolled: 22,
    successRate: 88,
    color: '#EDE9FE',
    meetings: [
      { day: '목', startHour: 11, endHour: 13 },
    ],
  },
  {
    id: 'KMU-GEN1207-01',
    lectureCode: '12053',
    sectionCode: '01',
    name: 'COLLEGE ENGLISH III',
    professor: 'Amy Park',
    room: '쉐턱관 204',
    credit: 2,
    category: '교양',
    liberalType: '공통교양',
    liberalArea: 'COLLEGE ENGLISH III',
    capacity: 30,
    enrolled: 21,
    successRate: 86,
    color: '#EDE9FE',
    meetings: [
      { day: '금', startHour: 9, endHour: 11 },
    ],
  },
  {
    id: 'KMU-GEN1301-01',
    lectureCode: '13010',
    sectionCode: '01',
    name: '교양세미나와토론',
    professor: '정다은',
    room: '백은관 215',
    credit: 3,
    category: '교양',
    liberalType: '공통교양',
    liberalArea: '교양세미나와토론',
    capacity: 35,
    enrolled: 28,
    successRate: 90,
    color: '#FCE7F3',
    meetings: [
      { day: '수', startHour: 13, endHour: 15 },
    ],
  },
  {
    id: 'KMU-GEN1401-01',
    lectureCode: '14010',
    sectionCode: '01',
    name: '기독교와계명인',
    professor: '이은혜',
    room: '아담스채플 101',
    credit: 2,
    category: '교양',
    liberalType: '공통교양',
    liberalArea: '기독교와계명인',
    capacity: 100,
    enrolled: 76,
    successRate: 96,
    color: '#E0F2FE',
    meetings: [
      { day: '월', startHour: 9, endHour: 11 },
    ],
  },
  {
    id: 'KMU-GEN1501-01',
    lectureCode: '15010',
    sectionCode: '01',
    name: '글로벌시티즌십',
    professor: '한지민',
    room: '동천관 304',
    credit: 2,
    category: '교양',
    liberalType: '공통교양',
    liberalArea: '글로벌시티즌십',
    capacity: 50,
    enrolled: 39,
    successRate: 92,
    color: '#D7F7F4',
    meetings: [
      { day: '화', startHour: 15, endHour: 17 },
    ],
  },
  {
    id: 'KMU-GEN1601-01',
    lectureCode: '16010',
    sectionCode: '01',
    name: 'AI와컴퓨팅사고',
    professor: '박민준',
    room: '공학1호관 1201',
    credit: 2,
    category: '교양',
    liberalType: '공통교양',
    liberalArea: 'AI와컴퓨팅사고',
    capacity: 60,
    enrolled: 48,
    successRate: 83,
    color: '#DAE8F8',
    meetings: [
      { day: '목', startHour: 15, endHour: 17 },
    ],
  },
  {
    id: 'KMU-GEN2101-01',
    lectureCode: '21010',
    sectionCode: '01',
    name: '현대사회와문화',
    professor: '오세준',
    room: '대명비사관 301',
    credit: 3,
    category: '교양',
    liberalType: '균형교양',
    liberalArea: '사회와문화',
    capacity: 45,
    enrolled: 34,
    successRate: 86,
    color: '#FCE7F3',
    meetings: [
      { day: '화', startHour: 13, endHour: 15 },
    ],
  },
  {
    id: 'KMU-GEN2201-01',
    lectureCode: '22010',
    sectionCode: '01',
    name: '진로설계와창업',
    professor: '강서윤',
    room: '바우어관 202',
    credit: 3,
    category: '교양',
    liberalType: '균형교양',
    liberalArea: '진로탐색/자기계발/창업',
    capacity: 45,
    enrolled: 25,
    successRate: 91,
    color: '#ECF9C8',
    meetings: [
      { day: '수', startHour: 15, endHour: 17 },
    ],
  },
  {
    id: 'KMU-GEN2251-01',
    lectureCode: '22510',
    sectionCode: '01',
    name: '글로벌리더십',
    professor: '한지민',
    room: '동천관 302',
    credit: 3,
    category: '교양',
    liberalType: '균형교양',
    liberalArea: '글로벌리더십',
    capacity: 45,
    enrolled: 27,
    successRate: 89,
    color: '#EDE9FE',
    meetings: [
      { day: '금', startHour: 11, endHour: 13 },
    ],
  },
  {
    id: 'KMU-GEN2302-01',
    lectureCode: '23020',
    sectionCode: '01',
    name: '과학기술과사회',
    professor: '박민준',
    room: '백은관 110',
    credit: 3,
    category: '교양',
    liberalType: '균형교양',
    liberalArea: '과학과기술',
    capacity: 45,
    enrolled: 28,
    successRate: 89,
    color: '#FDE68A',
    meetings: [
      { day: '수', startHour: 11, endHour: 13 },
    ],
  },
  {
    id: 'KMU-GEN2351-01',
    lectureCode: '23510',
    sectionCode: '01',
    name: '철학과역사의쟁점',
    professor: '남지후',
    room: '영암관 207',
    credit: 3,
    category: '교양',
    liberalType: '균형교양',
    liberalArea: '철학과역사',
    capacity: 40,
    enrolled: 30,
    successRate: 85,
    color: '#D9F1E8',
    meetings: [
      { day: '목', startHour: 9, endHour: 11 },
    ],
  },
  {
    id: 'KMU-GEN2411-01',
    lectureCode: '24110',
    sectionCode: '01',
    name: '문학과예술의이해',
    professor: '정다은',
    room: '대명비사관 402',
    credit: 3,
    category: '교양',
    liberalType: '균형교양',
    liberalArea: '문학과예술',
    capacity: 40,
    enrolled: 34,
    successRate: 80,
    color: '#FCE7F3',
    meetings: [
      { day: '목', startHour: 13, endHour: 15 },
    ],
  },
  {
    id: 'KMU-GEN3104-03',
    lectureCode: '31040',
    sectionCode: '03',
    name: '창의적사고와표현',
    professor: '최하늘',
    room: '교양관 204',
    credit: 2,
    category: '교양',
    liberalType: '일반교양',
    liberalArea: '일반교양',
    capacity: 30,
    enrolled: 18,
    successRate: 95,
    color: '#D7F7F4',
    meetings: [
      { day: '금', startHour: 15, endHour: 17 },
    ],
  },
  {
    id: 'KMU-EDU2101-01',
    lectureCode: '21011',
    sectionCode: '01',
    name: '교육학개론',
    professor: '서민정',
    room: '사범관 201',
    credit: 2,
    category: '교양',
    liberalType: '교직',
    liberalArea: '교직',
    capacity: 35,
    enrolled: 24,
    successRate: 88,
    color: '#FDE3E3',
    meetings: [
      { day: '수', startHour: 9, endHour: 11 },
    ],
  },
  {
    id: 'KMU-GEN4101-01',
    lectureCode: '41010',
    sectionCode: '01',
    name: '생활법률',
    professor: '장도현',
    room: '의양관 305',
    credit: 2,
    category: '교양',
    liberalType: '일반교양',
    liberalArea: '일반교양',
    capacity: 50,
    enrolled: 29,
    successRate: 93,
    color: '#E0F2FE',
    meetings: [
      { day: '월', startHour: 16, endHour: 18 },
    ],
  },
  {
    id: 'KMU-SPT1101-01',
    lectureCode: '11010',
    sectionCode: '01',
    name: '스포츠마케팅',
    professor: '문태준',
    room: '체육관 102',
    credit: 3,
    category: '전공',
    college: '체육대학',
    department: '체육학과',
    capacity: 35,
    enrolled: 22,
    successRate: 90,
    color: '#E0F2FE',
    meetings: [
      { day: '월', startHour: 9, endHour: 11 },
    ],
  },
  {
    id: 'KMU-KAC2101-01',
    lectureCode: '21012',
    sectionCode: '01',
    name: 'International Relations',
    professor: 'David Miller',
    room: '동천관 412',
    credit: 3,
    category: '전공',
    college: 'Keimyung Adams College',
    department: 'International Studies',
    capacity: 30,
    enrolled: 18,
    successRate: 92,
    color: '#EDE9FE',
    meetings: [
      { day: '화', startHour: 11, endHour: 13 },
    ],
  },
  {
    id: 'KMU-TRC1001-01',
    lectureCode: '10010',
    sectionCode: '01',
    name: '창의융합세미나',
    professor: '고은비',
    room: 'Tabula Rasa관 205',
    credit: 3,
    category: '전공',
    college: 'Tabula Rasa College',
    department: '창의융합학부',
    capacity: 40,
    enrolled: 26,
    successRate: 91,
    color: '#ECF9C8',
    meetings: [
      { day: '수', startHour: 11, endHour: 13 },
    ],
  },
  {
    id: 'KMU-PHA2201-01',
    lectureCode: '22011',
    sectionCode: '01',
    name: '약학개론',
    professor: '배수현',
    room: '약학관 301',
    credit: 3,
    category: '전공',
    college: '약학대학',
    department: '약학과',
    capacity: 35,
    enrolled: 33,
    successRate: 70,
    color: '#FDE68A',
    meetings: [
      { day: '목', startHour: 13, endHour: 15 },
    ],
  },
  {
    id: 'KMU-KCC2001-01',
    lectureCode: '20010',
    sectionCode: '01',
    name: '클라우드컴퓨팅기초',
    professor: '하민재',
    room: 'K-Cloud관 201',
    credit: 3,
    category: '전공',
    college: 'K-Cloud College',
    department: '클라우드컴퓨팅학과',
    capacity: 40,
    enrolled: 30,
    successRate: 84,
    color: '#DAE8F8',
    meetings: [
      { day: '금', startHour: 13, endHour: 15 },
    ],
  },
]

export function createTimetableEntries(lectures) {
  return lectures.flatMap(lecture =>
    lecture.meetings.map((meeting, index) => ({
      id: `${lecture.id}-${index}`,
      lectureId: lecture.id,
      name: lecture.name,
      professor: lecture.professor,
      room: lecture.room,
      lectureCode: lecture.lectureCode,
      sectionCode: lecture.sectionCode,
      credit: lecture.credit,
      color: lecture.color,
      day: meeting.day,
      startHour: meeting.startHour,
      startMinute: meeting.startMinute || 0,
      endHour: meeting.endHour,
      endMinute: meeting.endMinute || 0,
    }))
  )
}

// ── 시간표 데이터 ──
export const timetableData = createTimetableEntries(
  lectureCatalog.filter(lecture =>
    ['KMU-CSE1402-01', 'KMU-CSE2019-01', 'KMU-CSE2104-02'].includes(lecture.id)
  )
)

// ── 과제 데이터 ──
export const assignmentsData = [
  { id: 1, title: '컴퓨터구조 레포트 제출', due: '오늘 23:59 까지', urgency: 'today', done: false },
  { id: 2, title: '운영체제 프로세스 스케줄링 구현', due: 'D-3', urgency: 'soon', done: false },
  { id: 3, title: '데이터구조 알고리즘 문제 풀이', due: 'D-5', urgency: 'normal', done: false },
]

// ── 학점 계산기용 과목 ──
export const gradeCoursesData = [
  { id: 'crs-001', name: '웹어플리케이션구축', credit: 3, professor: '김교수', totalClass: 15, hwTotal: 5 },
  { id: 'crs-002', name: '데이터구조', credit: 3, professor: '이교수', totalClass: 14, hwTotal: 4 },
  { id: 'crs-003', name: '영어회화', credit: 2, professor: '박교수', totalClass: 12, hwTotal: 3 },
  { id: 'crs-004', name: '선형대수학', credit: 3, professor: '최교수', totalClass: 13, hwTotal: 6 },
  { id: 'crs-005', name: '운영체제', credit: 3, professor: '정교수', totalClass: 15, hwTotal: 4 },
]

// ── 수강신청 과목 풀 ──
export const coursePool = [
  { id: 'p001', name: '인공지능개론', credit: 3, professor: '강교수', quota: 40, enrolled: 38, time: '월/수 10:00~11:30' },
  { id: 'p002', name: '소프트웨어공학', credit: 3, professor: '윤교수', quota: 35, enrolled: 20, time: '화/목 09:00~10:30' },
  { id: 'p003', name: '컴퓨터네트워크', credit: 3, professor: '임교수', quota: 30, enrolled: 30, time: '월/수 14:00~15:30' },
  { id: 'p004', name: '모바일프로그래밍', credit: 3, professor: '신교수', quota: 25, enrolled: 10, time: '화/목 13:00~14:30' },
  { id: 'p005', name: '데이터베이스', credit: 3, professor: '조교수', quota: 40, enrolled: 35, time: '금 09:00~12:00' },
]
